# Input and output tasks
in_domains: depth-semseg
out_domains: rgb-depth-semseg
standardize_depth: True
extra_norm_pix_loss: False

# Architecture
model: pretrain_multimae_base
pretrained: False
decoder_dim: 256
input_size: 224
patch_size: 16
semseg_stride_level: 1
mask_type: gate-oriented
masked_rgb_gate_only: False
alphas: 1.0  # Dirichlet concentration parameter
num_encoded_tokens: 128 # Total would be 196 * 3 patches. 196 / 2 = 98
num_global_tokens: 1
decoder_use_task_queries: True
decoder_depth: 2

# Train
epochs: 300
opt: adamw
blr: 0.0001 # this is base_lr = 1e-4, lr = base_lr * batch_size / 256
warmup_lr: 0.000001 # 1e-6
min_lr: 0.
warmup_epochs: 40
batch_size: 64
hflip: 0.5
loss_on_unmasked: depth-semseg
fp32_output_adapters: semseg
eval_freq: 20

# Data
data_path: datasets/test/train # Change me
eval_data_path: datasets/test/val

# Wandb logging
log_wandb: True # Set to True to log to Weights & Biases
wandb_project: multimae-pretrain
wandb_entity: xingcw # Change if needed
wandb_log_dir: results
wandb_log_img: True
wandb_run_name: fine-semseg
output_dir: results/pretrain # Change directory if needed
